### ISSUE TITLE
Error	CS1929	'IDbConnection' does not contain a definition for 'FirstOrDefault' 

### ISSUE THREAD

**Issue by febitanya** [adebisi-fa/aspnet-identity-ormlite#2]
Severity	Code	Description	Project	File	Line	Column	Suppression State
Error	CS1929	'IDbConnection' does not contain a definition for 'FirstOrDefault' and the best extension method overload 'Queryable.FirstOrDefault<IdentityUser>(IQueryable<IdentityUser>, Expression<Func<IdentityUser, bool>>)' requires a receiver of type 'IQueryable<IdentityUser>'	AspNet.Identity.OrmLite	g:\DOWNLOADS - IE FOLDER\aspnet-identity-ormlite-master\src\AspNet.Identity.OrmLite\UserStore.cs	68	40	Active

**Comment by KAFCommunity** [comment]
you could replace FirstOrDefault by single it will return null if no results is returned

**Comment by febitanya** [comment]
Solved by Modifing Codes 
Thank You
